Social/Social/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account'))
]

Social/account/urls.py
from django.urls    import path
from .              import views


app_name = 'account'

urlpatterns = [
    path('register/',                   views.UserRegisterView.as_view(),               name='register'),
    path('login/',                      views.UserLoginView.as_view(),                  name='login'),
    path('logout/',                     views.UserLogoutView.as_view(),                 name='logout'),
    path('profile/<int:user_id>/',      views.UserProfileView.as_view(),                name='profile'),
    path('reset/',                      views.UserPasswordResetView.as_view(),          name='reset_password'),
    path('reset/done/',                 views.UserPasswordResetDoneView.as_view(),      name='password_reset_done'),
    path('confirm/<uidb64>/<token>/',   views.UserPasswordResetConfirmView.as_view(),   name='password_reset_confirm'),
    path('confirm/complete/',           views.UserPasswordResetCompleteView.as_view(),  name='password_reset_complete'),
    path('follow/<int:user_id>/',       views.UserFollowView.as_view(),                 name='user_follow'),
    path('unfollow/<int:user_id>/',     views.UserUnfollowView.as_view(),               name='user_unfollow'),
    path('edit_user/',                  views.EditUserView.as_view(),                   name='edit_user')
]   

Social/home/urls.py
from django.urls    import path
from .              import views


app_name = 'home'
urlpatterns = [
    path('',                                        views.HomeView.as_view(),           name='home'),
    path('post/<int:post_id>/<slug:post_slug>/',    views.PostDetailView.as_view(),     name='detail'),
    path('post/delete/<int:post_id>/',              views.PostDeleteView.as_view(),     name='delete'),
    path('post/update/<int:post_id>',               views.PostUpdateView.as_view(),     name='update'),
    path('post/create/',                            views.PostCreateView.as_view(),     name='create'),
    path('reply/<int:post_id>/<int:comment_id>/',   views.PostAddReplyView.as_view(),   name='add_reply'),
    path('like/<int:post_id>/',                     views.PostLikeView.as_view(),       name='post_like')
]

Social/templates/include/messages.html
{% if messages %}
    {% for msg in messages %}
    <p class="alert alert-{{msg.tags}}">{{msg}}</p>
    {% endfor %}
{% endif %}

Social/templates/include/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
          </li> 
          {% if request.user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link active"  href="{% url 'account:profile' request.user.id %}"> Profile </a> 
          </li> 
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'account:logout' %}">Logout</a>
          </li> 
          {% else %}
          <li class="nav-item">
            <a class="nav-link active"  href="{% url 'account:register' %}">Register</a> 
          </li> 
          <li class="nav-item">
            <a class="nav-link active"  href="{% url 'account:login' %}">Login</a> 
          </li> 

          {% endif %}
        </ul>
    </div>
  </nav>